# Generated by Django 3.1.7 on 2021-06-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Editor',
        ),
    ]
